version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 35
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 6
  similar-code:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 100
exclude_patterns:
  - "build/vuetify/"
  - "static/"
  - .codeclimate.yml
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
  - .gitignore
  - .postcssrc.js
  - .travis.yml
  - .vscode/
  - LICENSE
  - README.md
  - TODO.md
  - build/
  - icon.config.json
  - package.json
  - rollup.config.js
  - yarn.lock
  - webpack.config.js
  - tsconfig.json

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      extensions:
        - .js
        - .vue
