env:
  global:
    - CC_TEST_REPORTER_ID=f0287f41db52a0571bf958105718355d3a111a3d8e5d9ba36e6a4c8c69555b05
language: node_js
node_js:
  - "8"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - git clone --depth=1 https://github.com/darosh/gridy.git
  - cd gridy
  - yarn link
  - cd ..
  - yarn link gridy
  - git clone --depth=1 https://github.com/darosh/gridy-games-lib.git
  - cd gridy-games-lib
  - yarn link
  - cd ..
  - yarn link gridy-games-lib
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
