export const Constants = {
  FIRST_INDEX: 0,
  SECOND_INDEX: 1,
  MINIMAL_GAME_BOARD: 180,
  MOBILE_BREAKPOINT: 1264,
  RESIZE_REFRESH_DELAY: 100,
  SQUARE_RATIO: 1,
  DRAWER_WIDTH: 300,
  ZERO_WIDTH: 0,
  SHORT_BREAKPOINT: 800,
  GAME_MARGIN_X: 32,
  GAME_MARGIN_Y: 128,
  GAME_MARGIN_Y_SHORT: 80,
  GAME_FOOTER: 16
}

Object.freeze(Constants)
