export const AmplitudeEnvelope = require('tone/Tone/component/AmplitudeEnvelope')
export const Oscillator = require('tone/Tone/source/Oscillator')
export const Panner = require('tone/Tone/component/Panner')
export const PolySynth = require('tone/Tone/instrument/PolySynth')
export const Tone = require('tone/Tone/core/Tone')
